ALTER TABLE projects DROP COLUMN IF EXISTS tags;
ALTER TABLE simulations DROP COLUMN IF EXISTS tags;

ALTER TABLE projects ADD COLUMN tags TEXT[] NOT NULL DEFAULT '{}';
ALTER TABLE simulations ADD COLUMN tags TEXT[] NOT NULL DEFAULT '{}';